---
dataset:
  data_path: data_7c5b0e70
  #data_path_processed: data_089907f8_relationEnt_processed
  data_path_processed: data_7c5b0e70_atmarkEnt_onechoice
  #save_path: after_processTRAINdata.pkl
  train_file: /workdir/qagnn-main/data/clutrr/data_7c5b0e70/1.2,1.3_train.csv
  test_files: []
  load_dictionary: false
  train_test_split: 0.9
  train_val_split: 0.9
  max_vocab: -1
  tokenization: word
  common_dict: true
  sentence_mode: false #sentence mode processes each input story sentence separately. For GNN, this helps to maintaining a node pair -> sentence mapping
  process_bert: true
  bert_ent_format: atmark
  one_choice: true
  #//single_abs_line: true
model:
  batch_size: 32
  num_entity_block: 20
  loss_type: classify # set this to classify when performing a classification task, else `seq2seq`
  graph:
    edge_dim: 100
    num_reads: 1
